package com.voidcallerz.uc.registry;

import com.voidcallerz.uc.ModConstants;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import java.util.LinkedHashMap;
import java.util.Map;

public class UCItemRegistry {

    public static final DeferredRegister.Items ITEMS =
        DeferredRegister.createItems(ModConstants.MOD_ID);

    public static final Map<String, DeferredHolder<Item, Item>> ALL_ITEMS = new LinkedHashMap<>();

    // Compression catalyst — plain stacksTo(1) item.
    // craftRemainder self-reference causes unbound value errors in 1.21.2.
    // The item staying in the grid is handled via the "remainingItems" field
    // in the recipe JSON (generated by generate_data.py) instead.
    public static final DeferredHolder<Item, Item> UC_COMPRESSOR =
        ITEMS.registerItem("compression_catalyst",
            props -> new Item(props.stacksTo(1)));

    private static final Object[][] ITEMS_LIST = {
        { "compressed_raw_iron"        },
        { "compressed_raw_gold"        },
        { "compressed_raw_copper"      },
        { "compressed_iron_ingot"      },
        { "compressed_gold_ingot"      },
        { "compressed_copper_ingot"    },
        { "compressed_netherite_ingot" },
        { "compressed_diamond"         },
        { "compressed_emerald"         },
        { "compressed_amethyst_shard"  },
        { "compressed_quartz"          },
        { "compressed_lapis"           },
        { "compressed_redstone"        },
        { "compressed_flint"           },
        { "compressed_stick"           },
        { "compressed_leather"         },
        { "compressed_bone"            },
        { "compressed_string"          },
        { "compressed_feather"         },
        { "compressed_iron_nugget"     },
        { "compressed_gold_nugget"     },
        { "compressed_coal"            },
        { "compressed_blaze_rod"       },
    };

    static {
        for (Object[] entry : ITEMS_LIST) {
            String name = (String) entry[0];
            DeferredHolder<Item, Item> item = ITEMS.registerSimpleItem(name);
            ALL_ITEMS.put(name, item);
        }
    }
}