package com.voidcallerz.uc.registry;

import com.voidcallerz.uc.ModConstants;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemInstance;
import net.minecraft.world.item.ItemStackTemplate;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import java.util.LinkedHashMap;
import java.util.Map;

public class UCItemRegistry {

    public static final DeferredRegister.Items ITEMS =
        DeferredRegister.createItems(ModConstants.MOD_ID);

    public static final Map<String, DeferredHolder<Item, Item>> ALL_ITEMS = new LinkedHashMap<>();

    // Compression catalyst — plain stacksTo(1) item.
    // craftRemainder self-reference causes unbound value errors in 1.21.2.
    // The item staying in the grid is handled via the "remainingItems" field
    // in the recipe JSON (generated by generate_data.py) instead.
    public static final DeferredHolder<Item, Item> UC_COMPRESSOR =
        ITEMS.registerItem("compression_catalyst", props -> new Item(props.stacksTo(1)) {
            @Override
            public ItemStackTemplate getCraftingRemainder(ItemInstance instance) {
                return new ItemStackTemplate(this);
            }
        });

    private static final Object[][] ITEMS_LIST = {

        // --- Raw materials ---
        { "compressed_raw_iron",        0 },
        { "compressed_raw_gold",        0 },
        { "compressed_raw_copper",      0 },

        // --- Ingots ---
        { "compressed_iron_ingot",      0 },
        { "compressed_gold_ingot",      0 },
        { "compressed_copper_ingot",    0 },
        { "compressed_netherite_ingot", 0 },

        // --- Gems ---
        { "compressed_diamond",         0 },
        { "compressed_emerald",         0 },
        { "compressed_amethyst_shard",  0 },
        { "compressed_quartz",          0 },

        // --- Dusts & misc ---
        { "compressed_lapis",           0 },
        { "compressed_redstone",        0 },
        { "compressed_flint",           0 },
        { "compressed_stick",           900 },
        { "compressed_leather",         0 },
        { "compressed_bone",            0 },
        { "compressed_string",          0 },
        { "compressed_feather",         0 },
        { "compressed_resin_clump",     0 },

        // --- Nuggets ---
        { "compressed_iron_nugget",     0 },
        { "compressed_gold_nugget",     0 },

        // --- Fuels ---
        { "compressed_coal",            14400 },
        { "compressed_blaze_rod",       11200 },
    };

    static {
        for (Object[] entry : ITEMS_LIST) {
            String name = (String) entry[0];
            ALL_ITEMS.put(name, ITEMS.registerItem(name, Item::new));
        }
    }

    /** Every item with a non-zero burn time, as registry_name -> ticks. */
    public static Map<String, Integer> fuelItems() {
        Map<String, Integer> fuels = new LinkedHashMap<>();
        for (Object[] entry : ITEMS_LIST) {
            int burn = (int) entry[1];
            if (burn > 0) fuels.put((String) entry[0], burn);
        }
        return fuels;
    }
}